services:
  generation-service:
    build:
      context: ./generation_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./generation_service/.env.solo
    volumes:
      - ./generation_service/app:/app/app
    restart: always