services:
  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - ./ingestion-service/.env.solo
    volumes:
      - ./ingestion-service/app:/app/app
      - ingestion_uploads:/app/documents
    networks:
      - backend_internal
    restart: always

volumes:
  ingestion_uploads:
    driver: local

networks:
  backend_internal:
    external: true
