
@chromadb = http://localhost:8000
@rag-service = http://localhost:8001
@generation-service = http://localhost:8003
@retriever-service = http://localhost:8002
@ingestion-service = http://localhost:8004

GET {{chromadb}}/api/v2/heartbeat
###
GET http://localhost:8010/api/v2/heartbeat
###
GET http://127.0.0.1:8000/api/v2/heartbeat

###
GET {{rag-service}}/health
###
GET {{generation-service}}/health
###
GET {{retriever-service}}/health
###
GET {{ingestion-service}}/health



###
POST {{ingestion-service}}/api/v1/ingest

###
POST {{retriever-service}}/api/v1/retrieve
Content-Type: application/json

{
    "query": "everything about iphone"
}


###
POST {{generation-service}}/api/v1/generate
Content-Type: application/json

{
    "query": "What key information is provided about iPhone's safety, potential for medical device interference, and regulatory compliance?",
    "context_chunks": [
        "sound and in “Important safety information” in the  \niPhone User Guide .\nMedical Device Interference\niPhone contains magnets as well as components and/\nor radios that may interfere with medical devices. See \n“Important safety information” in the iPhone User Guide .\nRegulatory\nRegulatory certification information is available on-device. \nGo to Settings > General > Legal & Regulatory. Additional \nregulatory information is in “Safety, handling, and \nsupport” in the iPhone User Guide .\nFCC and ISED Canada Compliance\nThis device complies with part 15 of the FCC Rules and \nISED Canada licence-exempt RSS standard(s). Operation"
    ]
}


###
POST {{generation-service}}/api/v1/generate
Content-Type: application/json

{
    "query": "What key information is provided about iPhone's safety, potential for medical device interference, and regulatory compliance?",
    "context_chunks": [
        "sound and in “Important safety information” in the  \niPhone User Guide .\nMedical Device Interference\niPhone contains magnets as well as components and/\nor radios that may interfere with medical devices. See \n“Important safety information” in the iPhone User Guide .\nRegulatory\nRegulatory certification information is available on-device. \nGo to Settings > General > Legal & Regulatory. Additional \nregulatory information is in “Safety, handling, and \nsupport” in the iPhone User Guide .\nFCC and ISED Canada Compliance\nThis device complies with part 15 of the FCC Rules and \nISED Canada licence-exempt RSS standard(s). Operation"
    ]
}


###
POST {{rag-service}}/api/v1/chat
Content-Type: application/json

{
    "user_id": "1",
    "message": "What key information is provided about iPhone's safety, potential for medical device interference, and regulatory compliance?"
}