from pydantic import BaseModel, Field
from typing import List


class GenerateRequest(BaseModel):
    """Request model for generating an answer."""
    query: str = Field(..., description="The original user query.")
    context_chunks: List[str] = Field(..., description="List of relevant context chunks retrieved from the vector database.")


class GenerateResponse(BaseModel):
    """Response model containing the generated answer."""
    answer: str = Field(..., description="The final answer generated by the LLM.")